title: Change only this part
author: Me
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 Do your thing
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima
